### PR TITLE
Added Sales Functions

### PR DESCRIPTION
**Pull request by adrianmcli**
I also patched up a missing getOffer function and fixed up the readme file.

### CODE REVIEW

**Comment by SamyPesse** [comment]
Great :) Can you please remove the file `.DS_Store`:

```
$ git rm .DS_Store
$ git commit -m "Remove DS_Store:
$ git push
```

**Comment by SamyPesse** [comment]
Also checkout http://technicalpickles.com/posts/configure-git-to-globally-ignore-some-files/ to globally ignore `.DS_Store` ;)

**Comment by adrianmcli** [comment]
Ah okay, fixed! Do I have to make a new pull request, or can I do it from within this conversation?

**Comment by SamyPesse** [comment]
Thanks :+1:

**Comment by SamyPesse** [comment]
Published as `0.4.0`

**Pull request merged**
